# Generated by Django 5.0.7 on 2024-08-02 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stud_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
