# Generated by Django 5.0.7 on 2024-08-02 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stud_app', '0008_alter_customuser_user_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
