# Generated by Django 5.0.7 on 2024-08-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_app', '0013_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='session_year',
            name='duration',
            field=models.IntegerField(blank=True, default=4, null=True),
        ),
    ]
