# Generated by Django 5.0.7 on 2024-08-06 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stud_app', '0017_alter_subject_created_at_alter_subject_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='updated_at',
        ),
    ]
