# Generated by Django 5.0.7 on 2024-08-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_app', '0023_alter_subject_created_at_alter_subject_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_year',
            name='duration',
            field=models.IntegerField(default=4),
        ),
    ]
