# Generated by Django 5.0.7 on 2024-08-16 10:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_app', '0027_staff_leave'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff_leave',
            old_name='date',
            new_name='leave_end',
        ),
        migrations.AddField(
            model_name='staff_leave',
            name='leave_start',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
