# Generated by Django 5.0.7 on 2024-08-16 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stud_app', '0031_alter_staff_feedback_feedback_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_feedback',
            name='feedback_reply',
        ),
    ]
