# Generated by Django 5.0.7 on 2024-08-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_app', '0032_remove_staff_feedback_feedback_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_feedback',
            name='feedback_reply',
            field=models.TextField(blank=True),
        ),
    ]
