# Generated by Django 5.0.7 on 2024-08-17 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_app', '0036_student_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_leave',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stud_app.student'),
        ),
    ]
